databases:
  - name: postgres
    ipAllowList: []
    databaseName: budget_app
    user: budget_app

services:
  - type: web
    name: budget-app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: 06eac1c979397014d4e0cd482e61c536
        sync: false
     ipAllowList: []
     plan: free
     maxmemoryPolicy: noeviction