
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: postgres
  password: 719171

test:
  <<: *default
  database: budget_app_test
  username: postgres
  password: 719171


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: budget_app_production
  username: budget_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
